version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: foreveryoung
      POSTGRES_DB: echo_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://echo:changeme@postgres:5432/echo_dev
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app

  mobile:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./mobile:/app
    command: >
      sh -c "npm install &&
             npx expo start --tunnel"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

volumes:
  db_data:
